/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicioherencia;

public class App {

    public static void main(String[] args) {
        Employee emp = new Employee();
        emp.setName("Ken Wood");

        Manager mgr = new Manager();
        mgr.setName("Ken Furr");

        EmpUtil.printName(emp);
        EmpUtil.printName(mgr);

        Employee emp2;
        Manager mgr2 = new Manager();
        emp2 = mgr2;
        mgr2 = (Manager)emp2;

        /*Employee emp3;
        Manager mgr3 = new Manager();
        ParTimeManager ptm = new ParTimeManager();
        emp3 = mgr3;
        // ESTO PETA : ptm = (ParTimeManager)emp3;*/

        Manager mgr3 = new Manager();
        Employee emp3 = mgr3;
        if (emp3 instanceof Manager){
            mgr3 = (Manager) emp3;
        }
        else{
            System.out.println("Hola holita vecinito");
        }

        Employee employee = new Employee();
        employee.setName("John Jacobs");

        Manager manager = new Manager();
        manager.setName("John Jacobs");

        System.out.println(manager.equals(employee));
        System.out.println(employee.equals(manager));
        System.out.println(employee.equals("John Jacobs"));

    }
}
