/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicioherencia;

public class App {

    public static void main(String[] args) {
        Employee emp = new Employee();
        emp.setName("Ken Wood");

        Manager mgr = new Manager();
        mgr.setName("Ken Furr");

        EmpUtil.printName(emp);
        EmpUtil.printName(mgr);
    }
}
