/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicioherencia;

public class App {

    public static void main(String[] args) {
       LateBindingSuper lbSuper = new LateBindingSuper();
       LateBindingSub lbSub = new LateBindingSub();

       lbSuper.print();

       lbSub.print();
     ((LateBindingSuper)lbSub).print();

     lbSuper = lbSub;

     lbSuper.print();
    }
}
